# Generated by Django 3.2.9 on 2021-11-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionHandler',
            fields=[
                ('process_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('continue_run', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineLearningMethods',
            fields=[
                ('method', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author_id', models.BigIntegerField()),
                ('text', models.CharField(max_length=280)),
                ('lang', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField()),
                ('electoral_score', models.FloatField(null=True)),
                ('evaluation_method', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_screen_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=150)),
                ('user_verified', models.BooleanField()),
                ('user_location', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
