# Generated by Django 3.2.9 on 2021-11-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_machinelearningmethods'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearningMethods',
            fields=[
                ('method', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
