# Generated by Django 3.2.9 on 2021-12-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_machinelearningmethods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineLearningMethods',
            new_name='MachineLearningMethod',
        ),
    ]
