# Generated by Django 3.2.6 on 2021-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_machinelearningmethods_machinelearningmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='lang',
        ),
        migrations.AddField(
            model_name='tweet',
            name='like_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='quote_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='referenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='reply_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
