# Generated by Django 3.2.6 on 2021-12-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211213_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like_count',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quote_count',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='referenced',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='reply_count',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.SmallIntegerField(),
        ),
    ]
