# Generated by Django 3.2.6 on 2022-02-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211213_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
