# Generated by Django 3.2.6 on 2022-02-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tweet_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_screen_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_verified',
        ),
    ]
